
export const ActionTypes = {
    ADD_FOOD: "ADD_FOOD",
    READ_FOOD: "READ_FOOD",
    READ_FOOD_CATEGORY: "READ_FOOD_CATEGORY",
    COUNT_EVERY_FOOD_CATEGORY: "COUNT_EVERY_FOOD_CATEGORY",
    READ_SPECIFIC_FOOD_INFO: "READ_SPECIFIC_FOOD_INFO",
    RESET_SPECIFIC_FOOD_INFO: "RESET_SPECIFIC_FOOD_INFO",
    MODIFY_FOOD: "MODIFY_FOOD",
    UPDATE_FOOD_INFO: "UPDATE_FOOD_INFO",
    ARCHIVE_FOOD: "ARCHIVE_FOOD",
    ARCHIVE_FOOD_MESSAGE: "ARCHIVE_FOOD_MESSAGE",
    // SIGN_IN_USER: "SIGN_IN_USER",
    FETCH_PROFILE: "FETCH_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    LOG_IN_USER: "LOG_IN_USER",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOG_OUT_USER: "LOG_OUT_USER",
    MESSAGE_INFO: "MESSAGE_INFO",
    SINGLE_ERROR: "SINGLE_ERROR",
    CLEAR_ERROR_MSG: "CLEAR_ERROR_MSG"
}
